apiVersion: v1
kind: Pod
metadata:
   name: client-pod
   labels:
     component: web
spec:
  containers:
   - name: client
     image: prematv/complex_client
     ports:
        - containerPort: 8000
     resources:
         limits:
           memory: "128Mi"
           cpu: "500m"