version: '3'
services:
  # Nginx service
  nginx:
     build: ./nginx
     depends_on:
        - api
        - client
     ports:
        - "3050:80" 
  # postgres database
  postgres_db:
      image: "postgres"
      environment:
        - POSTGRES_PASSWORD=postgres_password

  # redis database
  redis_db:
    image: "redis"
  # API service
  api:
    build: ./server
    image:  "prematv/complex_api"
    environment:
         - REDIS_HOST=redis_db
         - REDIS_PORT=6379
         - PGHOST=postgres_db
         - PGPORT=5432
         - PGUSER=postgres
         - PGPASSWORD=postgres_password
         - PGDATABASE=postgres
          
  # work service
  worker:
    build: ./worker
    image: "prematv/complex_worker"
    environment: 
         - REDIS_HOST=redis
         - REDIS_PORT=6379
  #client service
  client:
     build: ./client
     image: "prematv/complex_client"